export enum Publisher {
	ROBOWHALE = "robowhale",
	GAME_DISTRIBUTION = "game-distribution",
	GAME_DISTRIBUTION_PREMIUM = "game-distribution-premium",
	GAME_DISTRIBUTION_ANDROID = "game-distribution-android",
	POKI = "poki",
	CRAZY_GAMES = "crazy-games",
	WORKER_BEE = "worker-bee",
	WORKER_BEE_NO_REWARDED = "worker-bee-no-rewarded",
	YANDEX = "yandex",
	VK = "vk",
	OK = "ok",
	FACEBOOK = "facebook",
	ORANGE_FRANCE = "orange-france",
	GAME_MONETIZE = "game-monetize",
	LAGGED = "lagged",
	UFREE_GAMES = "ufree-games",
	KILOO = "kiloo",
	GAME_REVSHARE = "game-revshare",
	GAMEPIX = "gamepix",
	OTHER = "other",
}
